sudo: false
language: go
go:
  - "1.x"
  - master
env:
  global:
    - CC_TEST_REPORTER_ID=a0af78184493a0c5dc13067047f619d9a202cb5af54e07ae1c8eedfd6a44c9ec
install:
  - go get -t -v ./...
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - go test -v -coverprofile=c.out ./...
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
matrix:
  allow_failures:
    - go: master
  fast_finish: true
addons:
  code_climate: true