name: Test

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - run: go get
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ['1.21', '1.22', '1.23']
    name: Go ${{ matrix.go }} test
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Installing dependencies
        run: go get
      - run: make test
